// THIS FILE IS AUTO-GENERATED BY FIGMAGIC. DO NOT MAKE EDITS IN THIS FILE! CHANGES WILL GET OVER-WRITTEN BY ANY FURTHER PROCESSING.

const fontSizes = {
 "h1": "24px",
 "h2": "20px",
 "h3Bold": "14px",
 "h3Regular": "14px",
 "h4Bold": "16px",
 "h4Regular": "12px",
 "paragraphBold": "14px",
 "paragraphRegular": "14px",
 "microcopy": "12px"
} as const;

export default fontSizes;