// THIS FILE IS AUTO-GENERATED BY FIGMAGIC. DO NOT MAKE EDITS IN THIS FILE! CHANGES WILL GET OVER-WRITTEN BY ANY FURTHER PROCESSING.

const radii = {
 "hard": "8px",
 "rounded": "12px",
 "soft": "16px",
 "circle": "100px"
} as const;

export default radii;