// THIS FILE IS AUTO-GENERATED BY FIGMAGIC. DO NOT MAKE EDITS IN THIS FILE! CHANGES WILL GET OVER-WRITTEN BY ANY FURTHER PROCESSING.

const spacing = {
 "extraSmall": "8px",
 "tiny": "10px",
 "meduim1": "16px",
 "medium2": "20px",
 "big": "30px",
 "large": "40px",
 "huge": "50px"
} as const;

export default spacing;